module.exports = [
    // Mouse Events
    'onclick',
    'oncontextmenu',
    'ondblclick',
    'onmousedown',
    'onmouseenter',
    'onmouseleave',
    'onmousemove',
    'onmouseover',
    'onmouseout',
    'onmouseup',
    // Keyboard Events
    'onkeydown',
    'onkeypress',
    'onkeyup',
    // Frame/Object Events
    'onabort',
    'onbeforeunload',
    'onerror',
    'onhashchange',
    'onload',
    'onpageshow',
    'onpagehide',
    'onresize',
    'onscroll',
    'onunload',
    // Form Events
    'onblur',
    'onchange',
    'onfocus',
    'onfocusin',
    'onfocusout',
    'oninput',
    'oninvalid',
    'onreset',
    'onsearch',
    'onselect',
    'onsubmit',
    // Drag Events
    'ondrag',
    'ondragend',
    'ondragenter',
    'ondragleave',
    'ondragover',
    'ondragstart',
    'ondrop',
    // Clipboard Events
    'oncopy',
    'oncut',
    'onpaste',
    // Print Events
    'onafterprint',
    'onbeforeprint',
    // Media Events
    'onabort',
    'oncanplay',
    'oncanplaythrough',
    'ondurationchange',
    'onemptied',
    'onended',
    'onerror',
    'onloadeddata',
    'onloadedmetadata',
    'onloadstart',
    'onpause',
    'onplay',
    'onplaying',
    'onprogress',
    'onratechange',
    'onseeked',
    'onseeking',
    'onstalled',
    'onsuspend',
    'ontimeupdate',
    'onvolumechange',
    'onwaiting',
    // Animation Events
    'animationend',
    'animationiteration',
    'animationstart',
    // Transition Events
    'transitionend',
    // Server-Sent Events
    'onerror',
    'onmessage',
    'onopen',
    // Misc Events
    'onmessage',
    'onmousewheel',
    'ononline',
    'onoffline',
    'onpopstate',
    'onshow',
    'onstorage',
    'ontoggle',
    'onwheel',
    // Touch Events
    'ontouchcancel',
    'ontouchend',
    'ontouchmove',
    'ontouchstart',
  ]